volumes:
  mongo_data:

services:
  redis:
    image: redis
    container_name: my_redis
    ports:
      - "6379:6379"

  mongo_db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: books
    volumes:
      - mongo_data:/var/lib/mongo/data
    ports:
      - "27017:27017"

  backend:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo_db
    environment:
      MONGO_URI: mongodb://mongo_admin:password@mongo_db:27017/books?authSource=admin

  tests:
    build: .
    depends_on:
      - backend
      - mongo_db
    environment:
      MONGO_URI: mongodb://mongo_admin:password@mongo_db:27017/books?authSource=admin
    command: pytest
